model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    #loss_type: l1
    first_stage_key: image
    
    image_size: 32 #32
    channels: 4 #4
    monitor: val/loss_simple_ema

    
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 #32
        in_channels: 4 #4
        out_channels: 4 #3#4
        model_channels: 256
        attention_resolutions:
        - 8
        - 4
        - 2
        - 1
        num_res_blocks: 2 #2
        channel_mult:
        - 1
        - 2
        - 2 #added
        - 4
        - 4
        
        num_heads: 8 # 32 #originally 32
        #use_spatial_transformer: true
        #transformer_depth: 1
        #context_dim: 512

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 4 #4
        n_embed: 16384 #8192
        ckpt_path: /ldm/VQGAN/vq-f8.ckpt  #YOUR VQF4
        ddconfig:
          double_z: false
          z_channels: 4 #4
          resolution: 256 #256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          #- 4 #added
          num_res_blocks: 2
          attn_resolutions: 
          - 32 #[]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: __is_unconditional__
      
data:
  target: main.DataModuleFromConfig
  params:
    batch_size:  64
    num_workers: 5
    wrap: False
    train:
      target: ldm.data.em.cropTrain
      params:
        size: 256
    validation:
      target: ldm.data.em.cropValidation
      params:
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 4
        increase_log_steps: False


  trainer:
    benchmark: True
